import dotenv from 'dotenv'
import { z } from 'zod'

dotenv.config()

const configSchema = z.object({
  port: z.coerce.number().default(3001),
  host: z.string().default('0.0.0.0'),
  
  // DeepSeek (now optional — users can configure providers via UI)
  deepseekApiKey: z.string().optional(),
  deepseekBaseUrl: z.string().default('https://api.deepseek.com/v1'),
  
  // Claude (optional)
  claudeApiKey: z.string().optional(),
  
  // Stable Diffusion (optional)
  sdApiUrl: z.string().optional(),
  sdApiKey: z.string().optional(),
  
  // Local model
  localModelEnabled: z.coerce.boolean().default(false),
  localModelBaseUrl: z.string().default('http://127.0.0.1:8080/v1'),
  localModelName: z.string().default('novelforge-qwen-lora'),
  
  // Database
  dbPath: z.string().default('./data/novelforge.db'),
  
  // Log
  logLevel: z.enum(['debug', 'info', 'warn', 'error']).default('info'),
  
  // CORS
  corsOrigins: z.string().optional().transform(val => val ? val.split(',').map(s => s.trim()) : undefined),
  
  // Auth — JWT secret is auto-generated by the setup wizard on first run.
  // For security, NEVER use the default value in production.
  jwtSecret: z.string().optional().transform(val => {
    if (process.env.NODE_ENV === 'test') {
      return val || 'test-jwt-secret'
    }
    // Return whatever is set (or undefined if not set — triggers setup mode)
    return val || undefined
  }),
  
  // Features
  featureCoverGeneration: z.coerce.boolean().default(true),
  featureScriptExport: z.coerce.boolean().default(true),
  featureAiDetection: z.coerce.boolean().default(true),
  featureStyleTransfer: z.coerce.boolean().default(true),
})

type Config = z.infer<typeof configSchema>

function loadConfig(): Config {
  const result = configSchema.safeParse({
    port: process.env.PORT,
    host: process.env.HOST,
    deepseekApiKey: process.env.DEEPSEEK_API_KEY,
    deepseekBaseUrl: process.env.DEEPSEEK_BASE_URL,
    claudeApiKey: process.env.CLAUDE_API_KEY,
    sdApiUrl: process.env.SD_API_URL,
    sdApiKey: process.env.SD_API_KEY,
    localModelEnabled: process.env.LOCAL_MODEL_ENABLED,
    localModelBaseUrl: process.env.LOCAL_MODEL_BASE_URL,
    localModelName: process.env.LOCAL_MODEL_NAME,
    dbPath: process.env.DB_PATH,
    logLevel: process.env.LOG_LEVEL,
    corsOrigins: process.env.CORS_ORIGINS,
    jwtSecret: process.env.JWT_SECRET,
    featureCoverGeneration: process.env.FEATURE_COVER_GENERATION,
    featureScriptExport: process.env.FEATURE_SCRIPT_EXPORT,
    featureAiDetection: process.env.FEATURE_AI_DETECTION,
    featureStyleTransfer: process.env.FEATURE_STYLE_TRANSFER,
  })
  
  if (!result.success) {
    console.error('Config validation error:')
    result.error.issues.forEach(issue => {
      console.error(`  ${issue.path.join('.')}: ${issue.message}`)
    })
    process.exit(1)
  }
  
  return result.data
}

export const config = loadConfig()
